{"name": "test_login_1_error[data0]", "status": "passed", "description": "异常登录", "attachments": [{"name": "log", "source": "1e36d3be-675e-44de-8356-08b6053a7411-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "47756801-6b81-4c3d-9fd4-36fc404f6cc5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': '', 'pwd': '', 'expected': '请输入手机号'}"}], "start": 1571367022017, "stop": 1571367029480, "uuid": "689ad316-a3c4-4609-bc91-ebe777d3adba", "historyId": "51efa93677dd5dab25fbeacbda681122", "testCaseId": "09a1dfa16a6f8824208fd27bb36bdeba", "fullName": "test_login.TestLogin#test_login_1_error", "labels": [{"name": "tag", "value": "demo"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-31LFQ9S"}, {"name": "thread", "value": "5408-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}