{"name": "test_login_1_error[data1]", "status": "passed", "description": "异常登录", "attachments": [{"name": "log", "source": "0a834ca7-b819-40bd-bc34-900cded81bbc-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': '123', 'pwd': '', 'expected': '请输入正确的手机号'}"}], "start": 1571367035606, "stop": 1571367044773, "uuid": "1a87ceca-4476-456f-b7f5-b86938c41e43", "historyId": "af66e56d33602761ce348aec2c1eee59", "testCaseId": "09a1dfa16a6f8824208fd27bb36bdeba", "fullName": "test_login.TestLogin#test_login_1_error", "labels": [{"name": "tag", "value": "demo"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-31LFQ9S"}, {"name": "thread", "value": "5408-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}