{"name": "test_login_1_error[data1]", "status": "passed", "description": "异常登录", "attachments": [{"name": "log", "source": "2fbb0bb3-e5cd-4dca-8b09-24333fe4d377-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': '123', 'pwd': '', 'expected': '请输入正确的手机号'}"}], "start": 1571302838974, "stop": 1571302844972, "uuid": "413d157a-b068-4e61-b793-b5b3bf2c692d", "historyId": "af66e56d33602761ce348aec2c1eee59", "testCaseId": "09a1dfa16a6f8824208fd27bb36bdeba", "fullName": "test_login.TestLogin#test_login_1_error", "labels": [{"name": "tag", "value": "demo"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-31LFQ9S"}, {"name": "thread", "value": "17160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}